"use client";
import { useEffect, useRef, useState, useTransition } from 'react';
import { useRouter } from 'next/navigation';
import { defaultDocument, fields, newLayer, readStudioDocument, studioKinds, validateStudio, type Layer, type Section, type StudioDocument, type StudioKind } from '@/lib/studio/model';
import { PassRenderer, WebsiteRenderer, type StudioData } from '@/components/studio-renderer';
import { saveStudio, publishStudio, retireStudio } from '@/app/admin/studio-actions';

type Version = { id:string; name:string; kind:string; status:string; revision:number; document:unknown; ticket_type_id:string|null; updated_at:string };
type Props = { eventId:string; versions:Version[]; tickets:{id:string;name:string}[]; data:StudioData; sampleQr:string };
export function DesignStudio({eventId,versions,tickets,data,sampleQr}:Props) {
  const router = useRouter();
  const [kind,setKind] = useState<StudioKind>('id_card');
  const [doc,setDoc] = useState<StudioDocument>(()=>defaultDocument('id_card'));
  const [name,setName] = useState('Untitled design');
  const [id,setId] = useState<string|null>(null);
  const [revision,setRevision] = useState(0);
  const [ticket,setTicket] = useState('');
  const [selected,setSelected] = useState('name');
  const [dirty,setDirty] = useState(false);
  const [message,setMessage] = useState('');
  const [pending,startTransition] = useTransition();
  const [mobile,setMobile] = useState(false);
  const [guide,setGuide] = useState(true);
  const [sampleName,setSampleName] = useState('Alexandra Morgan');
  const [history,setHistory] = useState<StudioDocument[]>([]);
  const [future,setFuture] = useState<StudioDocument[]>([]);
  const canvas = useRef<HTMLDivElement>(null);
  const drag = useRef<{id:string;x:number;y:number;left:number;top:number;document:StudioDocument}|null>(null);
  const currentLayer = doc.layers.find(l=>l.id===selected);
  const errors = validateStudio(doc,kind);
  const sample = {...data,name:sampleName,category:tickets.find(t=>t.id===ticket)?.name ?? 'General admission',code:'SAMPLE-001'};
  useEffect(()=>{
    if(!dirty)return;
    const unload=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};
    const navigate=(e:MouseEvent)=>{const anchor=(e.target as HTMLElement).closest('a[href]');if(anchor && !window.confirm('You have unsaved changes. Leave the design studio?'))e.preventDefault();};
    window.addEventListener('beforeunload',unload);document.addEventListener('click',navigate,true);
    return()=>{window.removeEventListener('beforeunload',unload);document.removeEventListener('click',navigate,true);};
  },[dirty]);
  function update(next:StudioDocument){setHistory(h=>[...h.slice(-29),doc]);setFuture([]);setDoc(next);setDirty(true);setMessage('');}
  function patchLayer(patch:Partial<Layer>){update({...doc,layers:doc.layers.map(l=>l.id===selected?{...l,...patch}:l)});}
  function newDesign(value:StudioKind){if(dirty&&!confirm('Discard unsaved changes?'))return;setKind(value);setDoc(defaultDocument(value));setId(null);setRevision(0);setName(`New ${value.replace('_',' ')}`);setTicket('');setDirty(false);setHistory([]);setFuture([]);setMessage('');}
  function load(v:Version){if(dirty&&!confirm('Discard unsaved changes?'))return;const next=readStudioDocument(v.document);if(!next)return;setDoc(next);setKind(v.kind as StudioKind);setId(v.status==='draft'?v.id:null);setRevision(v.status==='draft'?v.revision:0);setName(v.status==='draft'?v.name:`${v.name} copy`);setTicket(v.ticket_type_id??'');setDirty(v.status!=='draft');setHistory([]);setFuture([]);setMessage(v.status==='draft'?'Draft loaded.':'A new draft will be created from this version. The active version stays unchanged.');}
  async function save(copy=false){const result=await saveStudio({eventId,id:copy?null:id,revision,kind,name,ticketTypeId:ticket||null,document:doc});if(result.error){setMessage(result.error);return null;}setId(result.id!);setRevision(result.revision!);setDirty(false);setMessage('Draft saved. Participants still see the published version.');router.refresh();return result;}
  function publish(){if(errors.length){setMessage(errors.join(' '));return;}if(!confirm('Publish this design? It will replace the active design for this format and ticket category. Existing QR credentials remain valid.'))return;startTransition(async()=>{try{const saved=await save();if(!saved)return;const result=await publishStudio(eventId,saved.id!,saved.revision!);if(result.error)setMessage(result.error);else{setId(null);setRevision(0);setMessage('Published. Further edits will be saved as a new draft.');router.refresh();}}catch{setMessage('Connection interrupted. Check the version list before retrying.');}});}
  function moveLayer(delta:number){const index=doc.layers.findIndex(l=>l.id===selected);const target=index+delta;if(index<0||target<0||target>=doc.layers.length)return;const layers=[...doc.layers];[layers[index],layers[target]]=[layers[target],layers[index]];update({...doc,layers});}
  return <div className="design-studio">
    <header className="studio-toolbar"><div><span className="section-kicker">Design studio</span><h2>Pass layouts, made yours.</h2><p>Create a digital pass, ID card or wristband. Website design stays in Figma.</p></div><div className="resource-toolbar"><button className="button button-ghost" disabled={!history.length||pending} onClick={()=>{const prev=history.at(-1)!;setFuture(f=>[doc,...f]);setDoc(prev);setHistory(h=>h.slice(0,-1));setDirty(true);}}>Undo</button><button className="button button-ghost" disabled={!future.length||pending} onClick={()=>{setHistory(h=>[...h,doc]);setDoc(future[0]);setFuture(f=>f.slice(1));setDirty(true);}}>Redo</button><button className="button button-ghost" disabled={pending} onClick={()=>startTransition(async()=>{try{await save();}catch{setMessage('Unable to save. Try again.');}})}>Save draft</button><button className="button button-dark" disabled={pending||!!errors.length} onClick={publish}>{pending?'Working…':'Publish'}</button></div></header>
    {message&&<p className="studio-notice" role="status">{message}</p>}
    <fieldset className="studio-workspace" disabled={pending}>
      <aside className="studio-panel"><label>Format<select aria-label="Format" value={kind} onChange={e=>newDesign(e.target.value as StudioKind)}>{studioKinds.filter(k=>k!=='website').map(k=><option key={k} value={k}>{k.replace('_',' ')}</option>)}</select></label>
        <label>Design name<input value={name} maxLength={100} onChange={e=>{setName(e.target.value);setDirty(true);}}/></label>
        {kind!=='website'&&<label>Ticket category<select value={ticket} onChange={e=>{setTicket(e.target.value);setDirty(true);}}><option value="">Default for all categories</option>{tickets.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label>}
        <div className="studio-two"><label>Background<input type="color" value={doc.background} onChange={e=>update({...doc,background:e.target.value})}/></label><label>Accent<input type="color" value={doc.accent} onChange={e=>update({...doc,accent:e.target.value})}/></label></div>
        <label>Text color<input type="color" value={doc.foreground} onChange={e=>update({...doc,foreground:e.target.value})}/></label>
        <label>Typography<select value={doc.font} onChange={e=>update({...doc,font:e.target.value as StudioDocument['font']})}><option value="sans">Sans serif</option><option value="serif">Serif</option><option value="mono">Monospace</option></select></label>
        {kind!=='website'&&<><div className="studio-two"><label>Width (mm)<input type="number" min={20} max={500} value={doc.width} onChange={e=>update({...doc,width:Number(e.target.value)})}/></label><label>Height (mm)<input type="number" min={20} max={500} value={doc.height} onChange={e=>update({...doc,height:Number(e.target.value)})}/></label></div><button className="button button-ghost" onClick={()=>update({...doc,width:doc.height,height:doc.width})}>Swap orientation</button><h3>Layers</h3><small>Last layer is on top. Select a layer to edit or drag it.</small><div className="studio-layer-list">{doc.layers.map(l=><button key={l.id} aria-pressed={l.id===selected} onClick={()=>setSelected(l.id)}>{l.type==='text'?l.field:l.type}{l.hidden?' · hidden':''}{l.locked?' · locked':''}</button>)}</div><div className="resource-toolbar">{(['text','image','shape','qr'] as const).map(type=><button key={type} className="button button-ghost" onClick={()=>{const layer=newLayer(type);update({...doc,layers:[...doc.layers,layer]});setSelected(layer.id);}}>+ {type}</button>)}</div></>}
        {kind==='website'&&<><h3>Page sections</h3>{doc.sections.map((s,index)=><details key={s.id} className="studio-section-control"><summary>{s.type}{s.hidden?' · hidden':''}</summary><label>Heading<input value={s.title} onChange={e=>update({...doc,sections:doc.sections.map((v,i)=>i===index?{...v,title:e.target.value}:v)})}/></label><label>Content<textarea rows={5} value={s.body} onChange={e=>update({...doc,sections:doc.sections.map((v,i)=>i===index?{...v,body:e.target.value}:v)})}/></label><label>Image URL<input type="url" value={s.image} onChange={e=>update({...doc,sections:doc.sections.map((v,i)=>i===index?{...v,image:e.target.value}:v)})}/></label><div className="resource-toolbar"><button onClick={()=>update({...doc,sections:doc.sections.map((v,i)=>i===index?{...v,hidden:!v.hidden}:v)})}>{s.hidden?'Show':'Hide'}</button><button disabled={!index} onClick={()=>{const list=[...doc.sections];[list[index-1],list[index]]=[list[index],list[index-1]];update({...doc,sections:list});}}>Up</button><button disabled={index===doc.sections.length-1} onClick={()=>{const list=[...doc.sections];[list[index+1],list[index]]=[list[index],list[index+1]];update({...doc,sections:list});}}>Down</button><button onClick={()=>update({...doc,sections:doc.sections.filter((_,i)=>i!==index)})}>Remove</button></div></details>)}<label>Add section<select aria-label="Add section" value="" onChange={e=>{const type=e.target.value as Section['type'];update({...doc,sections:[...doc.sections,{id:crypto.randomUUID(),type,title:type.charAt(0).toUpperCase()+type.slice(1),body:'',image:'',hidden:false}]});}}><option value="">Choose a section</option>{['hero','description','schedule','location','gallery','faq','registration'].map(t=><option key={t}>{t}</option>)}</select></label></>}
      </aside>
      <section className="studio-preview-panel"><div className="resource-toolbar"><strong>Preview · {dirty?'Unsaved changes':'Saved state'}</strong>{kind==='website'?<button className="button button-ghost" onClick={()=>setMobile(!mobile)}>{mobile?'Desktop':'Mobile'} preview</button>:<label><input type="checkbox" checked={guide} onChange={e=>setGuide(e.target.checked)}/> Safe-area guide (2 mm)</label>}</div>
        {kind==='website'?<div className="studio-site-preview" style={{maxWidth:mobile?390:1000}}><WebsiteRenderer document={doc} data={sample} claimUrl="#" preview/></div>:<><label className="studio-sample">Test attendee name<input value={sampleName} onChange={e=>setSampleName(e.target.value)}/></label><div ref={canvas} className="studio-pass-canvas" style={{aspectRatio:`${doc.width}/${doc.height}`}} onPointerMove={e=>{if(!drag.current||!canvas.current)return;const rect=canvas.current.getBoundingClientRect();const state=drag.current;setDoc(d=>({...d,layers:d.layers.map(l=>l.id===state.id?{...l,x:Math.max(0,Math.min(d.width-l.width,state.left+(e.clientX-state.x)/rect.width*d.width)),y:Math.max(0,Math.min(d.height-l.height,state.top+(e.clientY-state.y)/rect.height*d.height))}:l)}));setDirty(true);}} onPointerUp={()=>{if(drag.current){const before=drag.current.document;setHistory(h=>[...h.slice(-29),before]);setFuture([]);}drag.current=null;}} onPointerCancel={()=>{drag.current=null;}}>
          <PassRenderer document={doc} data={sample} qr={sampleQr} guide={guide}/>
          {doc.layers.filter(l=>!l.hidden&&!l.locked).map(l=><button aria-label={`Move ${l.type} ${l.field}`} key={l.id} className={`studio-layer-hit ${l.id===selected?'is-selected':''}`} style={{left:`${l.x/doc.width*100}%`,top:`${l.y/doc.height*100}%`,width:`${l.width/doc.width*100}%`,height:`${l.height/doc.height*100}%`}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);setSelected(l.id);drag.current={id:l.id,x:e.clientX,y:e.clientY,left:l.x,top:l.y,document:doc};}} onKeyDown={e=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key))return;e.preventDefault();setSelected(l.id);update({...doc,layers:doc.layers.map(v=>v.id===l.id?{...v,x:Math.max(0,Math.min(doc.width-v.width,v.x+(e.key==='ArrowRight'?1:e.key==='ArrowLeft'?-1:0))),y:Math.max(0,Math.min(doc.height-v.height,v.y+(e.key==='ArrowDown'?1:e.key==='ArrowUp'?-1:0)))}:v)});}}/>)}
        </div><small>{doc.width} × {doc.height} mm · Sample QR only · Preview and print share the same renderer</small></>}
        {!!errors.length&&<div className="studio-validation" role="status"><strong>Before publishing</strong><ul>{errors.map(e=><li key={e}>{e}</li>)}</ul></div>}
      </section>
      <aside className="studio-panel">
        {kind!=='website'&&currentLayer&&<><h3>Layer properties</h3><label>Dynamic field<select value={currentLayer.field} disabled={currentLayer.locked} onChange={e=>patchLayer({field:e.target.value})}>{fields.map(f=><option key={f}>{f}</option>)}</select></label>{currentLayer.type==='text'&&<label>Static text<textarea value={currentLayer.text} disabled={currentLayer.locked} onChange={e=>patchLayer({text:e.target.value})}/></label>}{currentLayer.type==='image'&&<label>Image URL<input value={currentLayer.src} disabled={currentLayer.locked} onChange={e=>patchLayer({src:e.target.value})}/></label>}
          <div className="studio-two">{(['x','y','width','height','fontSize','radius'] as const).map(key=><label key={key}>{key} (mm)<input type="number" min={0} max={500} step="0.5" value={currentLayer[key]} disabled={currentLayer.locked} onChange={e=>patchLayer({[key]:Number(e.target.value)})}/></label>)}</div>
          <div className="studio-two"><label>Text color<input type="color" value={currentLayer.color} disabled={currentLayer.locked} onChange={e=>patchLayer({color:e.target.value})}/></label><label>Shape fill<input type="color" value={currentLayer.fill} disabled={currentLayer.locked} onChange={e=>patchLayer({fill:e.target.value})}/></label></div>
          <label>Text alignment<select value={currentLayer.align} disabled={currentLayer.locked} onChange={e=>patchLayer({align:e.target.value as Layer['align']})}><option>left</option><option>center</option><option>right</option></select></label><div className="resource-toolbar"><button disabled={currentLayer.locked} onClick={()=>patchLayer({x:(doc.width-currentLayer.width)/2})}>Center X</button><button disabled={currentLayer.locked} onClick={()=>patchLayer({y:(doc.height-currentLayer.height)/2})}>Center Y</button><button onClick={()=>moveLayer(1)}>Forward</button><button onClick={()=>moveLayer(-1)}>Backward</button></div><label><input type="checkbox" checked={currentLayer.locked} onChange={e=>patchLayer({locked:e.target.checked})}/> Lock layer</label><label><input type="checkbox" checked={currentLayer.hidden} onChange={e=>patchLayer({hidden:e.target.checked})}/> Hide layer</label><button className="button button-ghost" disabled={currentLayer.locked} onClick={()=>update({...doc,layers:doc.layers.filter(l=>l.id!==selected)})}>Delete layer</button></>}
        <p className="text-sm">Designing in Figma? Add a pass in the PassFlow plugin; it syncs here as a draft automatically.</p>
        <h3>Versions</h3><button className="button button-ghost" disabled={pending} onClick={()=>startTransition(async()=>{try{await save(true);}catch{setMessage('Unable to save a copy.');}})}>Save as new design</button><div className="studio-versions">{versions.map(v=><div key={v.id}><button onClick={()=>load(v)}><strong>{v.name}</strong><small>{v.kind} · {v.status} · v{v.revision}</small><small>{v.ticket_type_id?tickets.find(t=>t.id===v.ticket_type_id)?.name:'All categories'}</small></button>{v.status!=='archived'&&<button disabled={pending} onClick={()=>{if(!confirm(v.status==='draft'?'Delete this draft?':'Unpublish this version? Participants will see the next available fallback layout.'))return;startTransition(async()=>{try{const result=await retireStudio(eventId,v.id,v.revision,v.status==='draft');setMessage(result.error??'Version updated.');if(!result.error&&id===v.id){setId(null);setRevision(0);setDirty(true);}router.refresh();}catch{setMessage('Unable to update this version.');}});}}>{v.status==='draft'?'Delete draft':'Unpublish'}</button>}</div>)}</div>
      </aside>
    </fieldset>
  </div>;
}
