'use client';
import {useEffect,useState,useTransition} from 'react';
import {useRouter} from 'next/navigation';
import {createPairingCode,revokePluginLink} from '@/app/admin/figma-pairing-actions';
import {publishStudio,retireStudio} from '@/app/admin/studio-actions';
type Connection={id:string;file_name:string;expires_at:string;revoked_at:string|null;last_synced_at:string|null;external_change_at:string|null};
type Version={id:string;name:string;status:string;revision:number;updated_at:string};
export function FigmaPairingPanel({eventId,connections,versions,ready,now}:{eventId:string;connections:Connection[];versions:Version[];ready:boolean;now:number}){
  const [pending,startTransition]=useTransition(),[code,setCode]=useState(''),[message,setMessage]=useState('');
  const router=useRouter();
  useEffect(()=>{if(!ready)return;const timer=setInterval(()=>{if(document.visibilityState==='visible')router.refresh();},15000);return ()=>clearInterval(timer);},[ready,router]);
  function run(work:()=>Promise<{error?:string;success?:boolean;code?:string}>){startTransition(async()=>{try{const result=await work();setMessage(result.error??(result.code?'Code valid for 10 minutes. Creating another invalidates this code.':'Saved.'));if(result.code)setCode(result.code);}catch{setMessage('Connection interrupted. Please try again.');}});}
  return <div className="event-admin-stack"><section className="event-admin-section"><h2>Your event, designed in Figma.</h2><p>Open an existing Figma file, run PassFlow, then pair this event. Start with a template or choose Advanced Mode. Sync updates a draft, never the live site.</p><ol><li>Open your Figma file and the standard PassFlow plugin.</li><li>Generate a code below and enter it under Pair Event.</li><li>Insert a starter template, edit, preview and publish here.</li></ol><div className="resource-toolbar"><button className="button button-dark" disabled={pending||!ready} onClick={()=>run(()=>createPairingCode(eventId))}>Generate pairing code</button><a className="button button-ghost" href="/figma-plugin-standard.zip" download>Download standard plugin</a></div>{code&&<p><strong style={{fontFamily:'monospace',fontSize:24,userSelect:'all'}}>{code}</strong></p>}{!ready&&<p role="status">Pairing requires the database migration and server configuration. No connection is active yet.</p>}<p className="text-sm">The older account plugin does not support this pairing flow. The download includes development-install instructions.</p></section>
    {message&&<p role="status" className="studio-notice">{message}</p>}
    <section className="event-admin-section"><h3>Paired files</h3>{!connections.length&&<p>No paired files yet.</p>}{connections.map(c=><div key={c.id} className="resource-record"><strong>{c.file_name}</strong><p>{c.revoked_at?'Revoked':Date.parse(c.expires_at)<now?'Expired':c.external_change_at?'Changes detected outside the plugin':c.last_synced_at?'Synced':'Connected, awaiting first sync'}</p>{c.last_synced_at&&<small>Last sync (UTC): {new Date(c.last_synced_at).toLocaleString('en-GB',{timeZone:'UTC'})}</small>}{!c.revoked_at&&<button className="button button-ghost" disabled={pending} onClick={()=>{if(confirm('Revoke this plugin connection? Existing published designs remain live.'))run(()=>revokePluginLink(eventId,c.id));}}>Revoke connection</button>}</div>)}</section>
    <section className="event-admin-section"><h3>Drafts & published versions</h3>{!versions.length&&<p>Insert a template and sync from Figma to create the first draft.</p>}{versions.map(v=><div key={v.id} className="resource-record"><strong>{v.name}</strong><p>{v.status} · version {v.revision}</p><div className="resource-toolbar"><a className="button button-ghost" href={`/admin/events/${eventId}/design/preview/${v.id}`}>Preview</a>{v.status==='draft'&&<button className="button button-dark" disabled={pending} onClick={()=>{if(confirm('Publish this reviewed version? Only the live website design changes. Tickets and QR credentials stay unchanged.'))run(()=>publishStudio(eventId,v.id,v.revision));}}>Publish</button>}{v.status==='published'&&<button className="button button-ghost" disabled={pending} onClick={()=>{if(confirm('Unpublish and return to the fallback event page?'))run(()=>retireStudio(eventId,v.id,v.revision,false));}}>Unpublish</button>}</div></div>)}</section>
  </div>;
}
