import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFigmaWebsite,validateFigmaWebsite,websiteLink} from '../lib/figma-website.ts';
import {eventHostLabel,validEventLabel,normalizeEventLabel} from '../lib/event-host.ts';
const layer={id:'stable-metadata',type:'box',x:20,y:20,width:200,height:60,text:'Register',binding:'register'};
const doc=()=>({schema:2,source:'figma',desktop:{width:1440,height:900,nodes:[{...layer}]},mobile:null});
test('nested schema rejects missing parents and cycles',()=>{const raw={...doc(),schema:3};raw.desktop.nodes=[{...layer,id:'section',binding:null,parentId:null},{...layer,id:'cta',parentId:'section',x:0,y:0}];assert.ok(readFigmaWebsite(raw));raw.desktop.nodes[0].parentId='cta';assert.equal(readFigmaWebsite(raw),null);raw.desktop.nodes[0].parentId='missing';assert.equal(readFigmaWebsite(raw),null);});
test('metadata bindings survive visible layer rename',()=>{const raw=doc();raw.desktop.nodes[0].name='Renamed freely';const parsed=readFigmaWebsite(raw);assert.equal(parsed.desktop.nodes[0].binding,'register');assert.deepEqual(validateFigmaWebsite(parsed),[]);});
test('invalid payloads and unsafe images/actions are rejected',()=>{for(const bad of [{schema:1}, {...doc(),desktop:{width:Infinity,height:900,nodes:[]}}])assert.equal(readFigmaWebsite(bad),null);const raw=doc();raw.desktop.nodes.push({...layer});assert.equal(readFigmaWebsite(raw),null);raw.desktop.nodes=[{...layer,type:'image',image:'data:image/svg+xml;base64,AAAA'}];assert.equal(readFigmaWebsite(raw),null);for(const value of ['javascript:alert(1)','//evil.example','data:text/html,hi','http://example.com'])assert.equal(websiteLink(value),'');});
test('publishing checks both responsive frames and actions',()=>{const raw=doc();raw.mobile={width:390,height:800,nodes:[{...layer,binding:null}]};assert.match(validateFigmaWebsite(readFigmaWebsite(raw)).join(' '),/Mobile needs/);raw.desktop.nodes[0].x=1400;assert.match(validateFigmaWebsite(readFigmaWebsite(raw)).join(' '),/beyond/);});
test('host routing accepts only exact valid child domains',()=>{assert.equal(eventHostLabel('Discoveries.passflow.my.id'),'discoveries');for(const host of ['passflow.my.id.evil.com','a.b.passflow.my.id','admin.passflow.my.id','discoveries.passflow.my.id:443','discoveries.passflow.my.id.','evil.com'])assert.equal(eventHostLabel(host),null);assert.equal(normalizeEventLabel(' Discoveries '),'discoveries');for(const name of ['api','www','login','support','xn--test','ab','-event','event-','event.name'])assert.equal(validEventLabel(name),false);});

test('venue map is an accepted dynamic binding',()=>{const raw=doc();raw.desktop.nodes.push({...layer,id:'map',binding:'venueMap',x:20,y:120,width:400,height:220});const parsed=readFigmaWebsite(raw);assert.ok(parsed);assert.equal(parsed.desktop.nodes.find(n=>n.id==='map').binding,'venueMap');});

test('hover and scroll anchors parse safely',()=>{const raw={...doc(),schema:3};raw.desktop.nodes=[{...layer,id:'cta',hover:{fill:'#111111',color:'#ffffff',opacity:.9,ms:180,ease:'ease-out;background:url(https://evil.example)'}},{...layer,id:'jump',binding:'customLink',href:'#s1-2',y:100},{...layer,id:'target',binding:null,anchor:'s1-2',y:200}];const parsed=readFigmaWebsite(raw);assert.ok(parsed);const cta=parsed.desktop.nodes.find(n=>n.id==='cta');assert.equal(cta.hover.ease,'ease-out');assert.equal(cta.hover.fill,'#111111');assert.equal(parsed.desktop.nodes.find(n=>n.id==='target').anchor,'s1-2');assert.deepEqual(validateFigmaWebsite(parsed),[]);parsed.desktop.nodes.find(n=>n.id==='target').anchor='';assert.match(validateFigmaWebsite(parsed).join(' '),/Scroll to target/);});

test('extra pages: reserved names rejected, page links checked, Register only required on Home',()=>{const page=slug=>({slug,desktop:{width:1440,height:600,nodes:[{...layer,binding:null,id:'p-'+slug}]}});const raw={...doc(),schema:3,pages:[page('ticket'),page('agenda')]};raw.desktop.nodes.push({...layer,id:'go',binding:'customLink',href:'page:agenda',y:100});const parsed=readFigmaWebsite(raw);assert.ok(parsed);assert.equal(parsed.pages.length,2);assert.deepEqual(validateFigmaWebsite(parsed),[]);for(const bad of ['claim','api','Agenda','-x'])assert.equal(readFigmaWebsite({...raw,pages:[page(bad)]}),null,bad);parsed.desktop.nodes.find(n=>n.id==='go').href='page:missing';assert.match(validateFigmaWebsite(parsed).join(' '),/not synced \(missing\)/);assert.equal(websiteLink('page:claim'),'');assert.equal(websiteLink('page:home'),'page:home');});

test('parity fields: storage images, gradients, shadows, spans, fonts, alpha and tablet',()=>{const url='https://tghllarxwuhdbmtfewsa.supabase.co/storage/v1/object/public/event-assets/e/figma/abc.png';const raw={...doc(),schema:3,tablet:{width:834,height:900,nodes:[{...layer}]}};raw.desktop.nodes.push({...layer,id:'hero',binding:null,y:100,fill:'#ff000080',bg:{image:url,fit:'contain'},gradient:{type:'linear',angle:90,stops:[{color:'#000000',pos:0},{color:'#ffffff00',pos:1}]},shadows:[{x:0,y:8,blur:24,spread:0,color:'#0000001a'}],enter:'up'},{...layer,id:'t',type:'text',binding:null,y:200,text:'Hello bold world',fontFamily:'Playfair Display',italic:true,spans:[{start:6,end:10,weight:700,color:'#ff0000'},{start:20,end:30}]});const p=readFigmaWebsite(raw);assert.ok(p);const hero=p.desktop.nodes.find(n=>n.id==='hero'),t=p.desktop.nodes.find(n=>n.id==='t');assert.equal(hero.fill,'#ff000080');assert.equal(hero.bg.fit,'contain');assert.equal(hero.gradient.stops.length,2);assert.equal(hero.shadows[0].blur,24);assert.equal(hero.enter,'up');assert.equal(t.fontFamily,'Playfair Display');assert.equal(t.italic,true);assert.equal(t.spans.length,1,'out-of-range span dropped');assert.equal(p.tablet.width,834);for(const bad of ['https://evil.example/x.png','https://x.supabase.co/storage/v1/object/public/attendee-photos/a.png']){const r=structuredClone(raw);r.desktop.nodes[1].bg.image=bad;assert.equal(readFigmaWebsite(r),null,bad);}const f=structuredClone(raw);f.desktop.nodes[2].fontFamily='Bad;Font';assert.equal(readFigmaWebsite(f).desktop.nodes.find(n=>n.id==='t').fontFamily,'Inter');});
