import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFigmaWebsite,validateFigmaWebsite,websiteLink} from '../lib/figma-website.ts';
import {eventHostLabel,validEventLabel,normalizeEventLabel} from '../lib/event-host.ts';
const layer={id:'stable-metadata',type:'box',x:20,y:20,width:200,height:60,text:'Register',binding:'register'};
const doc=()=>({schema:2,source:'figma',desktop:{width:1440,height:900,nodes:[{...layer}]},mobile:null});
test('nested schema rejects missing parents and cycles',()=>{const raw={...doc(),schema:3};raw.desktop.nodes=[{...layer,id:'section',binding:null,parentId:null},{...layer,id:'cta',parentId:'section',x:0,y:0}];assert.ok(readFigmaWebsite(raw));raw.desktop.nodes[0].parentId='cta';assert.equal(readFigmaWebsite(raw),null);raw.desktop.nodes[0].parentId='missing';assert.equal(readFigmaWebsite(raw),null);});
test('metadata bindings survive visible layer rename',()=>{const raw=doc();raw.desktop.nodes[0].name='Renamed freely';const parsed=readFigmaWebsite(raw);assert.equal(parsed.desktop.nodes[0].binding,'register');assert.deepEqual(validateFigmaWebsite(parsed),[]);});
test('invalid payloads and unsafe images/actions are rejected',()=>{for(const bad of [{schema:1}, {...doc(),desktop:{width:Infinity,height:900,nodes:[]}}])assert.equal(readFigmaWebsite(bad),null);const raw=doc();raw.desktop.nodes.push({...layer});assert.equal(readFigmaWebsite(raw),null);raw.desktop.nodes=[{...layer,type:'image',image:'data:image/svg+xml;base64,AAAA'}];assert.equal(readFigmaWebsite(raw),null);for(const value of ['javascript:alert(1)','//evil.example','data:text/html,hi','http://example.com'])assert.equal(websiteLink(value),'');});
test('publishing checks both responsive frames and actions',()=>{const raw=doc();raw.mobile={width:390,height:800,nodes:[{...layer,binding:null}]};assert.match(validateFigmaWebsite(readFigmaWebsite(raw)).join(' '),/Mobile needs/);raw.desktop.nodes[0].x=1400;assert.match(validateFigmaWebsite(readFigmaWebsite(raw)).join(' '),/beyond/);});
test('host routing accepts only exact valid child domains',()=>{assert.equal(eventHostLabel('Discoveries.passflow.my.id'),'discoveries');for(const host of ['passflow.my.id.evil.com','a.b.passflow.my.id','admin.passflow.my.id','discoveries.passflow.my.id:443','discoveries.passflow.my.id.','evil.com'])assert.equal(eventHostLabel(host),null);assert.equal(normalizeEventLabel(' Discoveries '),'discoveries');for(const name of ['api','www','login','support','xn--test','ab','-event','event-','event.name'])assert.equal(validEventLabel(name),false);});

test('venue map is an accepted dynamic binding',()=>{const raw=doc();raw.desktop.nodes.push({...layer,id:'map',binding:'venueMap',x:20,y:120,width:400,height:220});const parsed=readFigmaWebsite(raw);assert.ok(parsed);assert.equal(parsed.desktop.nodes.find(n=>n.id==='map').binding,'venueMap');});
