import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
try{
await db.exec(`
create role anon;create role authenticated;create role service_role bypassrls;
create schema auth;create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create table events(id uuid primary key,name text,slug text,status text,organization_id uuid);
create table organization_members(organization_id uuid,user_id uuid,role text);
create function public.is_event_manager(p_event_id uuid) returns boolean language sql stable security definer as $$select exists(select 1 from public.events e join public.organization_members m on m.organization_id=e.organization_id where e.id=p_event_id and m.user_id=auth.uid() and m.role in ('owner','admin'))$$;
create table ticket_types(id uuid primary key,event_id uuid);
create type station_mode as enum('check_in','zone_access','activity','claim');
create table access_zones(id uuid primary key,event_id uuid,name text,code text,description text);
create table activities(like access_zones including all);create table benefits(like access_zones including all);alter table benefits add is_active boolean default true;
create table scanner_stations(id uuid primary key,event_id uuid,name text,mode station_mode,zone_id uuid,config jsonb,is_active boolean);
create table scan_logs(id uuid,scanner_station_id uuid);create table activity_logs(id uuid,activity_id uuid,scanner_station_id uuid);
create table benefit_claims(id uuid,event_id uuid,benefit_code text,scanner_station_id uuid);create table access_rules(id uuid primary key,event_id uuid,zone_id uuid);
create table event_designs(id uuid primary key,event_id uuid,kind text,ticket_type_id uuid,updated_at timestamptz);
`);
for(const file of ['20260927152845_management_design_lifecycle.sql','20260928043603_figma_plugin_pairing.sql','20260928045356_event_subdomains.sql'])await db.exec(fs.readFileSync('supabase/migrations/'+file,'utf8'));
const user='11111111-1111-4111-8111-111111111111',event='22222222-2222-4222-8222-222222222222',second='33333333-3333-4333-8333-333333333333',org='44444444-4444-4444-8444-444444444444';
await db.exec(`insert into auth.users values('${user}');insert into events values('${event}','First','first','published','${org}'),('${second}','Second','second','draft','${org}');insert into organization_members values('${org}','${user}','owner');grant usage on schema public,auth to anon,authenticated,service_role;grant select on events,ticket_types to authenticated,anon;grant all on all tables in schema public to service_role;set test.uid='${user}';set role authenticated;`);
const rpc=async(sql,args=[]) => (await db.query('select '+sql+' as result',args)).rows[0].result;
await assert.rejects(()=>rpc("exchange_figma_pairing_code('x','y','document1','File',null,'ip')"),/permission denied/);
await assert.rejects(()=>db.query('select token_hash from figma_plugin_links'),/permission denied/);
await rpc('create_figma_pairing_code($1,$2)',[event,'a'.repeat(64)]);
await db.exec('reset role;set role service_role;');
const pair=async(code,token,bucket='ip')=>rpc('exchange_figma_pairing_code($1,$2,$3,$4,null,$5)',[code,token,'document1','My renamed file',bucket]);
const linked=await pair('a'.repeat(64),'b'.repeat(64));assert.equal(linked.eventId,event);
assert.equal((await pair('a'.repeat(64),'c'.repeat(64))).error,'invalid_pairing_code');
for(let i=0;i<10;i++)assert.equal((await pair('d'.repeat(64),'e'.repeat(64),'guess')).error,'invalid_pairing_code');
assert.equal((await pair('d'.repeat(64),'e'.repeat(64),'guess')).error,'rate_limited');
const sync=async(revision,document={schema:2,source:'figma'},hash='initial')=>rpc('figma_plugin_draft($1,$2,$3,$4,$5)',['b'.repeat(64),'document1',revision,document,hash]);
const draft=await sync(0);assert.equal(draft.revision,1);
assert.deepEqual(await sync(0),draft); // Retry with same payload is idempotent.
assert.equal((await sync(0,{schema:2,source:'figma',changed:true},'changed')).error,'revision_conflict');
assert.equal((await sync(1,{},'bad')).error,'invalid_document');
await db.exec('reset role;set role anon;');
assert.equal((await db.query('select count(*)::int n from event_studio_documents')).rows[0].n,0);
await assert.rejects(()=>rpc("figma_plugin_draft('x','document1',0)"),/permission denied/);
await db.exec('reset role;set role authenticated;');
await rpc('publish_studio_document($1,$2,1)',[event,draft.draftId]);
await db.exec('reset role;set role service_role;');
const next=await sync(1,{schema:2,source:'figma',changed:true},'changed');assert.notEqual(next.draftId,draft.draftId);
assert.equal((await db.query('select status from event_studio_documents where id=$1',[draft.draftId])).rows[0].status,'published');
await db.query('update figma_plugin_links set file_key=$1 where id=$2',['verifiedFile123',linked.id]);
await rpc("mark_figma_external_change('verifiedFile123',now()+interval '1 second')");
assert.ok((await db.query('select external_change_at from figma_plugin_links where id=$1',[linked.id])).rows[0].external_change_at);
assert.equal((await db.query('select count(*)::int n from event_studio_documents')).rows[0].n,2);
await db.exec('reset role;set role authenticated;');
await rpc('save_event_subdomain($1,$2)',[event,'discoveries']);
assert.equal(await rpc('check_event_subdomain($1,$2)',[second,'discoveries']),false);
await assert.rejects(()=>rpc('save_event_subdomain($1,$2)',[second,'discoveries']),/duplicate key/);
await assert.rejects(()=>rpc('save_event_subdomain($1,$2)',[event,'admin']),/invalid_subdomain/);
await rpc('save_event_subdomain($1,$2)',[second,'hidden-event']);
await rpc('create_figma_pairing_code($1,$2)',[event,'f'.repeat(64)]);
await db.exec("reset role;set role service_role;update figma_pairing_codes set expires_at=now()-interval '1 minute' where consumed_at is null;");
assert.equal((await pair('f'.repeat(64),'e'.repeat(64),'expiry')).error,'invalid_pairing_code');
await db.exec('reset role;set role authenticated;');
await db.exec('reset role;set role anon;');
assert.equal(await rpc("resolve_event_subdomain('discoveries')"),'first');assert.equal(await rpc("resolve_event_subdomain('hidden-event')"),null);
await db.exec(`reset role;set role authenticated;update figma_plugin_links set revoked_at=now() where id='${linked.id}';reset role;set role service_role;`);
assert.equal((await sync(1)).error,'connection_expired');
await db.exec(`reset role;update figma_plugin_links set revoked_at=null;delete from organization_members;set role service_role;`);
assert.equal((await sync(1)).error,'permission_revoked');
await db.exec(`reset role;set role authenticated;`);
await assert.rejects(()=>rpc('create_figma_pairing_code($1,$2)',[event,'f'.repeat(64)]),/not_authorized/);
assert.equal((await db.query('select count(*)::int n from figma_plugin_links')).rows[0].n,0);
console.log('PASS: pairing permissions, single use, committed rate limit, secret isolation, draft-only sync, idempotence, conflicts, publish fork, revocation, membership loss, reserved/unique/published-only subdomains');
}catch(error){console.error(error.message);process.exitCode=1;}finally{await db.close();}
