import { PGlite } from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
(async()=>{const db=new PGlite();await db.exec(`
create role anon;create role authenticated;create schema auth;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
create type public.station_mode as enum('check_in','zone_access','activity','claim');
create table events(id uuid primary key, status text,manager uuid);
create function public.is_event_manager(p_event_id uuid) returns boolean language sql stable as $$select exists(select 1 from public.events where id=p_event_id and manager=auth.uid())$$;
create table ticket_types(id uuid primary key,event_id uuid);
create table access_zones(id uuid primary key,event_id uuid,name text,code text,description text);
create table activities(like access_zones including all);
create table benefits(like access_zones including all);alter table benefits add is_active boolean default true;
create table scanner_stations(id uuid primary key,event_id uuid,name text,mode station_mode,zone_id uuid,config jsonb,is_active boolean);
create table scan_logs(id uuid,scanner_station_id uuid);
create table activity_logs(id uuid,activity_id uuid,scanner_station_id uuid);
create table benefit_claims(id uuid,event_id uuid,benefit_code text,scanner_station_id uuid);
create table access_rules(id uuid primary key,event_id uuid,zone_id uuid);
create table event_designs(id uuid primary key,event_id uuid,kind text,ticket_type_id uuid,updated_at timestamptz);
`);await db.exec(fs.readFileSync('supabase/migrations/20260927152845_management_design_lifecycle.sql','utf8'));
const uid='11111111-1111-4111-8111-111111111111',event='22222222-2222-4222-8222-222222222222',station='33333333-3333-4333-8333-333333333333';
await db.exec(`insert into auth.users values('${uid}');insert into events values('${event}','published','${uid}');set test.uid='${uid}';grant usage on schema auth to authenticated,anon;grant select,insert,update,delete on public.scanner_stations,public.access_zones,public.activities,public.benefits,public.scan_logs,public.activity_logs,public.benefit_claims,public.access_rules to authenticated;grant select,update on public.events to authenticated;grant select on public.ticket_types,public.event_designs to authenticated;insert into scanner_stations values('${station}','${event}','Gate','check_in',null,'{}',true);`);
await db.exec('set role authenticated');
await db.query(`select manage_event_resource($1,$2,'station','update',$3)`,[event,station,{name:'Main entrance',mode:'check_in'}]);
await db.exec(`insert into scan_logs values(gen_random_uuid(),'${station}')`);

await assert.rejects(()=>db.query(`select manage_event_resource($1,$2,'station','delete','{}')`,[event,station]),/record_in_use/);
await db.query(`select manage_event_resource($1,$2,'station','deactivate','{}')`,[event,station]);
assert.equal((await db.query('select is_active from scanner_stations')).rows[0].is_active,false);
await db.exec(`set test.uid='44444444-4444-4444-8444-444444444444'`);
await assert.rejects(()=>db.query(`select manage_event_resource($1,$2,'station','update',$3)`,[event,station,{name:'Attack',mode:'check_in'}]),/not_authorized/);
await db.exec(`set test.uid='${uid}'`);
const save=await db.query(`select save_studio_document($1,null,0,'id_card',null,'Draft','{"schema":1}') as result`,[event]);const id=save.rows[0].result.id;
await assert.rejects(()=>db.query(`select save_studio_document($1,$2,0,'id_card',null,'Stale','{}')`,[event,id]),/revision_conflict/);
await db.query('select publish_studio_document($1,$2,1)',[event,id]);
await assert.rejects(()=>db.query(`select save_studio_document($1,$2,2,'id_card',null,'Overwrite','{}')`,[event,id]),/revision_conflict/);
const second=(await db.query(`select save_studio_document($1,null,0,'id_card',null,'Second','{"schema":1}') as result`,[event])).rows[0].result.id;
await db.query('select publish_studio_document($1,$2,1)',[event,second]);
assert.deepEqual((await db.query('select status from event_studio_documents order by created_at,id')).rows.map(r=>r.status).sort(),['archived','published']);
await assert.rejects(()=>db.exec("update public.event_studio_documents set status='published'"),/permission denied/);
await db.exec('reset role;grant select on public.events to anon;set role anon;');
assert.equal((await db.query('select count(*)::int as n from event_studio_documents')).rows[0].n,1);
console.log('PASS: migration, gate edit/history protection, deactivation, authorization, stale revision, immutable publishing, archived versions, anonymous isolation');await db.close();})().catch(e=>{console.error(e);process.exit(1)});
